services:
  mysql_db:
    build: ./db
    container_name: mysql_db
    expose:
      - '3306'

  backend:
    environment:
      - JDBC_USERNAME=${JDBC_USERNAME}
      - JDBC_URL=${JDBC_URL}
      - JDBC_PASSWORD=${JDBC_PASSWORD}
      - GROWBIZ_SECRET_KEY=${GROWBIZ_SECRET_KEY}
    build: ./backend
    depends_on:
      - mysql_db
    container_name: backend
    ports:
      - '9002:9002'
    expose:
      - '9002'
  
  frontend:
    build: ./frontend
    depends_on:
      - backend
      - mysql_db
    ports:
      - '3000:3000'
    expose:
      - '3000'